[JY-125] Firebase를 사용하여 Email, google 로그인 기능을 구현한다.
DONOTINTO/AirPlan pull request #3
Opened 2023-07-12 13:46 UTC by DONOTINTO

카드번호 : [JY-125](https://keentutoring.atlassian.net/browse/JY-125)

2023-07-13 06:14 UTC, keenkim1202 requested changes

2023-07-13 06:14 UTC, keenkim1202 commented on AirPlan/AirPlan/AppDelegate.swift
> +    func application(_ app: UIApplication,
공식문서에서 코드를 가져왔어도 기존 swift 컨벤션을 준수하여 작성해주세요!

2023-07-13 06:14 UTC, keenkim1202 commented on AirPlan/AirPlan/Controller/LoginViewController.swift
> +        loginView.initialSetup()
`self.view = loginView`
코드를 제외한 나머지 함수는 `viewDidLoad()` 로 옮겨주세요~!

2023-07-13 06:14 UTC, keenkim1202 commented on AirPlan/AirPlan/Controller/LoginViewController.swift
> +    //일반 이메일 - 로그인 버튼 클릭 시
```suggestion
    // 일반 이메일 - 로그인 버튼 클릭 시
```
기본적으로 주석을 생성하면 슬래시 뒤에 공백 하나가 있습니다. 다른 주석들도 체크하여 준수해주세요!

2023-07-13 06:14 UTC, keenkim1202 commented on AirPlan/AirPlan/Controller/LoginViewController.swift
> +        Auth.auth().signIn(withEmail: email, password: password) { [weak self] authResult, error in
어떤 함수에서는 이 사이를 한줄 띄고, 어떤 함수에서는 띄지 않았습니다.
통일해주세요!

2023-07-13 06:14 UTC, keenkim1202 commented on AirPlan/AirPlan/Controller/LoginViewController.swift
> +            guard let user = result?.user, let idToken = user.idToken?.tokenString else {
`return` 값이 없다면 한 줄로 작성해주세요

2023-07-16 09:23 UTC, DONOTINTO commented
@keenkim1202 
수정 완료했습니다!

2023-07-16 11:07 UTC, keenkim1202 commented
@DONOTINTO 
머지하겠습니다! 아래의 링크 부분의 컨벤션만 향후 준수해주세요~!
- https://github.com/DONOTINTO/AirPlan/pull/3/files#r1262037650

2023-07-16 11:07 UTC, keenkim1202 approved these changes

2023-07-16 11:07 UTC, merged