[JY-128] 금일 날짜를 표기한다.
DONOTINTO/AirPlan pull request #5
Opened 2023-07-16 10:05 UTC by DONOTINTO

카드번호 : [JY-128](https://keentutoring.atlassian.net/browse/JY-128)

2023-07-16 11:14 UTC, keenkim1202 requested changes
코멘트 확인 후 필요한 부분 수정 부탁드립니다!

2023-07-16 11:14 UTC, keenkim1202 commented on AirPlan/AirPlan/Controller/LoginViewController.swift
> +        loginView.initialSetup()
이 부분은 이전 JY-125 카드 관련 PR 에서 수정헀던 내용인데, 지금 그대로 머지하게 되면 변경사항이 사라집니다.
loadView() 에서는 `self.view = loginView` 만 실행하고 나머지는 `viewDidLoad()` 로 옮겨주세요~!

2023-07-16 11:14 UTC, keenkim1202 commented on AirPlan/AirPlan/Controller/LoginViewController.swift
> +        loginView.loginButton.addTarget(self, action: #selector(loginButtonClicked), for: .touchUpInside)
버튼에 액션을 추가하는 라인이 4줄이 있습니다.
한 두개이면 `viewDidLoad()` 안에 바로 작성할 수도 있지만, 
그 이상이라면 `addButtonsAction()` 과 같은 함수를 만들어 함수로 분리하면 더 좋을 것 같습니다.

2023-07-16 11:14 UTC, keenkim1202 commented on AirPlan/AirPlan/Controller/LoginViewController.swift
> +            guard let user = result?.user, let idToken = user.idToken?.tokenString else {
```suggestion
            guard let user = result?.user, let idToken = user.idToken?.tokenString else { return }
```

2023-07-16 11:14 UTC, keenkim1202 commented on AirPlan/AirPlan/Model/IQAirDate.swift
> +class IQAirDate {
선택)
어떤 용도를 위해 만든 커스텀 클래스인지 위에 주석으로 설명을 추가해주시면 
다른 개발자가 의도를 파악하기 용이할 것 같습니다.

2023-07-16 11:14 UTC, keenkim1202 commented on AirPlan/AirPlan/SceneDelegate.swift
> +        #if DEBUG
전처리기를 사용하여 분기처리하는 것 좋습니다~! 🙌

2023-07-16 11:14 UTC, keenkim1202 commented on AirPlan/AirPlan/View/LoginView.swift
> +        [idTextField, passwordTextField, loginButton, signUpButton, signInGoogleButton, testLabel, testLogOutButton].forEach { self.addSubview($0)}
```suggestion
        [idTextField, passwordTextField, loginButton, signUpButton, signInGoogleButton, testLabel, testLogOutButton].forEach { self.addSubview($0) }
```

2023-07-16 11:14 UTC, keenkim1202 commented on AirPlan/AirPlan/View/LoginView.swift
> +        testLabel.snp.makeConstraints{
```suggestion
        testLabel.snp.makeConstraints {
```

2023-07-16 11:14 UTC, keenkim1202 commented
@DONOTINTO 
+ 지라카드의 상태가 `BACKLOG`로 되어있어서 제가 `IN REVIEW` 로 변경해두었습니다.

2023-07-16 13:24 UTC, DONOTINTO commented
@keenkim1202 
수정했습니다!

2023-07-17 15:36 UTC, keenkim1202 commented
@DONOTINTO 컨벤션 준수가 되지 않은 부분은 큰 이슈가 아니므로 머지처리하겠습니다~

2023-07-17 15:36 UTC, merged